### ISSUE TITLE
Failed to open favorite folders in drive

### ISSUE THREAD

**Issue by flo-st** [FilenCloudDienste/filen-web#20]
**Describe the bug**
When navigating to Drive > Favorites, double-clicking a favorite folder does not open the folder. Instead, the path updates in the UI and URL, but the folder remains stuck in a loading animation that fades in and out.

**To Reproduce**
1. Go to 'Drive > Favorites'
2. Click on any favorite folder
3. Watch the path update in the UI and URL
4. Notice that the folder is stuck in a loading animation

**Expected behavior**
Favorite folders should open when clicked and display their contents without loading problems.

**Browser and OS (please complete the following information):**
 - OS: Windows 10
 - Firefox 132.0.2

**Additional context**
Files within favorites can be opened without problems.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-web/commit/a3c6ed2adfe185df6de6dcb09cb19a4aa490e495
