### ISSUE TITLE
2FA recovery key should be hidden when entering

### ISSUE THREAD

**Issue by Eagleshot** [FilenCloudDienste/filen-web#21]
**Describe the bug**
2FA recovery key should be hidden when entering it during login.

**To Reproduce**
1. Log in with 2FA enabled
2. Select "Use recovery key instead".
3. Enter the key

**Expected behavior**
The recovery key should be a hidden as default when entering it (like the password).

**Screenshots**
![image](https://github.com/user-attachments/assets/446daace-4ce7-47c1-aff7-f715ec3a11d8)

**Browser and OS (please complete the following information):**
- Firefox

**Additional context**
-

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-web/commit/e0983d5aa6a919619b7f887b603688a3b1019d6d
