### ISSUE TITLE
Account IDs (Alternative to email for sharing files with other users)

### ISSUE THREAD

**Issue by trymeouteh** [FilenCloudDienste/filen-web#22]
**Is your feature request related to a problem? Please describe.**
To share files with other users. I must share my account email address

**Describe the solution you'd like**
To be able to share an unique generated ID instead of my email address.

To not allow other Filen users to see my account email address.

**Describe alternatives you've considered**
None

**Additional context**
For better privacy

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io
