### ISSUE TITLE
Filen website consumes too many resources

### ISSUE THREAD

**Issue by SaifulLukman** [FilenCloudDienste/filen-web#23]
**Describe the bug**
When I visited this page yesterday, Filen caused my browser and my laptop to freeze.
I visited your site again today and the page doesn't freeze but it still consumes a lot of resources. See screenshot please.
I am not logged in to Filen and there are no other tabs running besides Filen. 
It doesn't seem to be my extensions either. Even if I turn off uBlock Origin and Brave's built-in ad blocker, the problem persists.

<details><summary>Screenshot</summary>

![filen io-bug](https://github.com/user-attachments/assets/89310b55-fff5-4cfc-80fd-ac1709154136)

</details>

**Browser and OS (please complete the following information):**
 - OS: Windows 10
 - Browser including version : Brave 1.73.89 Chromium: 131.0.6778.69
 - VPN/Proxy used : Cloudflare 1.1.1.1 DNS
 - Browser extensions : uBlock Origin, Bitwarden, Simple Translate, Search by Image, Video Control for Instagram

**Additional context**

**Comment by Dwynr** [comment]
Are you on a lower-end machine? This is most likely caused by the confetti rendering canvas on the pricing page.
