### ISSUE TITLE
Stuck on creating directories

### ISSUE THREAD

**Issue by sjiawjbssj** [FilenCloudDienste/filen-web#25]
**Describe the bug**
When uploading a folder with a lot of sub-folders the transfer list stays stuck at showing creating directories instead of the progress bar.

**To Reproduce**
1. Upload Folder with a lot of sub-folders
2. open transfers

**Expected behavior**
The progress bar should show the current status of the upload

**Screenshots**
![Screenshot](https://github.com/user-attachments/assets/b0d78465-b347-454d-a750-1b134a35a9de)

**Browser and OS (please complete the following information):**
 - OS: Windows
 - Browser including version: Brave [Version 1.73.89 Chromium: 131.0.6778.69]
 - VPN used
 - Browser extensions: uBlock, DarkReader, Decentraleyes

**Comment by Dwynr** [comment]
If it's _a lot_ of subfolders, then it's probably not stuck, just taking long. The app has to create all directories before uploading any files. I'd let it run for a bit. Nonetheless I'd also recommend using a one-way "local backup" sync in our desktop client. It handles uploads of large directory trees much more efficient than a browser ever could.

**Comment by Dwynr** [comment]
We'll try to make the progress more clear.
