### ISSUE TITLE
Sharing below link for Filen Team to refer and get some new ideas and find Missing Features and Competitor Comparison.

### ISSUE THREAD

**Issue by libbyslayer** [FilenCloudDienste/filen-web#26]
Sharing below link for Filen Team to refer and get some new ideas and find Missing Features and Competitor Comparison.

https://docs.google.com/spreadsheets/d/1cEd65XDW3gBHnRsJ0rbq3V_B28mKySHiMPAZvArHiiA/edit?gid=0#gid=0

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io
