### ISSUE TITLE
Consider a Switch to an Alternative Payment Provider for Crypto

### ISSUE THREAD

**Issue by Eggroley** [FilenCloudDienste/filen-web#27]
**Is your feature request related to a problem? Please describe.**

Coinbase Commerce was updated this year to exclusively accept UTXO-based cryptocurrencies, requiring users to have a KYC-verified Coinbase account. This change restricts payments from popular cryptocurrencies like BTC, LTC, BCH, and XMR unless users undergo verification which is impossible in many countries due to regulations.

Coinbase now only supports payments through EVM chains like Ethereum, Polygon, and Base. However, this is a problem for many users who prefer UTXO chains. Additionally, most tokens on EVM chains are centralized (meaning assets can get frozen), have high fees, lack privacy, or are prone to failure, making them unsuitable as a payment method... Because of this, users are forced to pay extra in exchange fees just to switch to another currency. Following this often results in a leftover balance in a currency you don't want or trust.

**Describe the solution you'd like**

Switch to an alternative payment provider that accepts payments from UTXO chains. 

I know of a few alternatives like nowpayments and coinpayments which have worked well for me in the past.

**Comment by skieop** [comment]
+1 from me, this is the only thing stopping me buying a large lifetime plan.

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io
