### ISSUE TITLE
Cookie banner interferes with "Report abuse" button

### ISSUE THREAD

**Issue by Eagleshot** [FilenCloudDienste/filen-web#28]
**Describe the bug**
The Cookie banner interferes with "Report abuse" button on a public download link.

**To Reproduce**
1. Create a public link to a file
2. Open public link
3. ...

**Expected behavior**
The visibility should be given for both elements.

**Screenshots**
If applicable, add screenshots/recordings to help explain your problem.
![image](https://github.com/user-attachments/assets/93e7ed7d-4e0c-435b-bc43-767188d7f02a)

**Browser and OS (please complete the following information):**
 - Firefox

**Additional context**
-

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-web/commit/81113781a299939b59d06c5c863cd146d1cf1bd2
