### ISSUE TITLE
Nitpick: Saving a public link should close the dialog.

### ISSUE THREAD

**Issue by Eagleshot** [FilenCloudDienste/filen-web#29]
**Describe the bug**
When creating a public link, you first need to save the settings, then close it, which is annoying if you need to share several files.

**To Reproduce**
1. Create a public link.
2. Save the options.
3. Close the dialog.

**Expected behavior**
Saving the settings of a public link should close the dialog.

**Screenshots**
If applicable, add screenshots/recordings to help explain your problem.
![Screenshot 2024-11-24 at 14-16-39 Filen](https://github.com/user-attachments/assets/0e6cbafb-f199-4b5a-911f-9a58a24896ac)

**Browser and OS (please complete the following information):**
 - Firefox

**Additional context**
-

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-web/commit/990a03608c972e94bdcd45c7c455a23c0debe32d
