### ISSUE TITLE
storage used bar UI style

### ISSUE THREAD

**Issue by kuyagic** [FilenCloudDienste/filen-web#30]
**Describe the bug**
The UI color is difficult to make the file and the file version used clear to display

**To Reproduce**
go to settings , General

**Expected behavior**
use different color to show file and file version used.

**Screenshots**
![image](https://github.com/user-attachments/assets/c6c4c449-7551-449f-9dcc-0315c9d41ceb)
Both used color seem to be black.

**Browser and OS (please complete the following information):**
Vivaldi latest version

**Additional context**

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io
