### ISSUE TITLE
Markdown viewer issues (web)

### ISSUE THREAD

**Issue by BlastboomStrice** [FilenCloudDienste/filen-web#31]
**Describe the bug**
Hello, I think after a recent update, the markdown viewer (both in notes and .md files viewer) seems not to work properly:
The lists (both ordered and unordered, either nested or simple) don't have a number or a bullet next to each element, as it used to.

Also, while this might be me not knowing markdown well enough, if at the beginning of the line you write `<number>. <number>. ` it will create a latin-numbered list that will display the latin numbers for some reason. I couldn't find any guide on creating latin-numbered lists so I don't know if that's an expected behavior, but it's cool.

**To Reproduce**
Simply create a .md note, create any kind of ordered/unordered/simple/nested list and preview it on the web. It won't display the numbers/bullets.

**Expected behavior**
It should create lists with the numbers/bullets next to each list element.

**Screenshots**
Web md previewer:
![Web](https://github.com/user-attachments/assets/373e3bf6-aa6a-46f7-976d-01a0446703fd)

Android app md previewer:
![Screenshot_2024-11-24-20-51-04-363_io filen app_1](https://github.com/user-attachments/assets/16cb7aa9-4ad1-47d6-b6f8-88fe3efee83a)

**Browser and OS (please complete the following information):**
The same happens both on my pc and my phone
PC: 
- OS: Windows 10
 - Browser including version: Firefox beta 133.0 (64-bit)
 - VPN/Proxy used: none
 - Browser extensions: (I have various, but the ones that might affect the filen page are probably ublock origin and consent-o-matic)

Android (Xiaomi Mi 10)
- OS: Android 13 HyperOS 1.0
 - Browser including version: Fennec F-Droid 132.0.0
 - VPN/Proxy used: none
 - Browser extensions: (I have various, but the ones that might affect the filen page are probably ublock origin and consent-o-matic)
 
**Additional context**
Thank you for your work people :)

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-web/commit/4ece1e65cc6da1f4573408781fbe1003cc0a3b2c
