### ISSUE TITLE
Preview: chunk download

### ISSUE THREAD

**Issue by sibyo** [FilenCloudDienste/filen-web#32]
**Describe the bug**
The file preview keeps fetching chunks even after the preview modal has been closed. 
Hi, could you look into this? It's causing high memory usage, and my RAM is struggling.

Fixing this issue should also help reduce server load by preventing the unnecessary fetching of chunks that are no longer needed.

**Comment by Dwynr** [comment]
We've achieved on-demand video/file streaming for previews inside the web app internally. Should also fix this issue.
