### ISSUE TITLE
iOS app: files and folders not showing their actual names.

### ISSUE THREAD

**Issue by mastino21** [FilenCloudDienste/filen-web#35]
**Describe the bug**
please see attached screenshot, self explanatory.

**To Reproduce**
just open the app, deleting app cache does not fix it. Closing/reopening app does not fix it.
![photo_2024-11-25_15-11-14](https://github.com/user-attachments/assets/31faa463-a74a-4eba-b473-face67c116c7)

**Expected behavior**
I should see proper file and folder names

**Screenshots**
enclosed

**Browser and OS (please complete the following information):**
 - OS: iOS 18.1.1
 - Iphone 15

**Comment by Dwynr** [comment]
Wrong repository. Not a bug. Disable the "Hide folder and file names" setting.
