### ISSUE TITLE
Duplicate phrase?

### ISSUE THREAD

**Issue by SaifulLukman** [FilenCloudDienste/filen-web#36]
The top and bottom explanations are almost very similar. 

Explanation 1 is not needed in my opinion.

Explanation number 2 can stay there because it seems to be enough.

https://i.postimg.cc/zfwzKfxn/image.png

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-web/commit/668c79355b379d6443f555e4897d0b236121c7e5
