### ISSUE TITLE
Consider to add the function of downloading/sharing directly from the preview of pictures/videos on the web page. 

### ISSUE THREAD

**Issue by zhangbalabala** [FilenCloudDienste/filen-web#37]
**Is your feature request related to a problem? Please describe.**
Currently I need to exit the image preview before I can share/download the file. Once the file name exceeds the number that can be displayed on the interface, I will not be able to find the image that has just been previewed. And after exiting the preview and switching views, the interface will suddenly jump back to the top, making it difficult to find the file I just previewed.

**Describe the solution you'd like**
As shown in the following figure: When previewing a picture, if the user wants to download the picture/video, after moving the mouse cursor to the file name in the upper left corner or clicking the file name, a drop-down menu will appear, providing buttons for sharing, creating a public link, and downloading. 

**Describe alternatives you've considered**
None

**Additional context**
For faster and easier downloading/sharing.
![IMG_1932](https://github.com/user-attachments/assets/4cae22ae-5914-4660-98af-181536188785)

**Comment by zhangbalabala** [comment]
And it would be better if the preview image could display Exif information.
Button:Exif Info

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io
